stages:
  check_for_new_data:
    cmd: python3 -m src.data.check_for_new_data
    params:
    - download.url
    - download.last_updated
    deps:
    - params.yaml
    outs:
    - data/last_updated.txt

  collect_data:
    cmd: python3 -m src.data.collect_and_extract ${download.url} --out 
      ${download.out}
    params:
    - download.url
    - download.out
    deps:
    - src/data/collect_and_extract.py
    - params.yaml
    - data/last_updated.txt
    outs:
    - data/raw/creditcard.csv

  preprocess:
    cmd: python3 -m src.data.preprocess
    deps:
    - data/raw/creditcard.csv
    - src/data/preprocess.py
    params:
    - preprocess.raw_data_path
    - preprocess.processed_data_path
    - preprocess.scale_columns
    outs:
    - data/processed/processed_creditcard.csv

  split:
    cmd: python3 -m src.train.split
    deps:
    - src/train/split.py
    - data/processed/processed_creditcard.csv
    params:
    - split.processed_data_path
    - split.train_data_path
    - split.validation_data_path
    - split.test_data_path
    - split.target_column
    - split.test_size
    - split.random_state
    outs:
    - data/train/train_original.npz
    - data/train/train_resampled.npz
    - data/validation/valid.npz
    - data/test/X_test.json
    - data/test/y_test.json

  train_and_evaluate:
    cmd: python3 -m src.train.run_train
    deps:
    - data/train/train_original.npz
    - data/train/train_resampled.npz
    - data/validation/valid.npz
    - params.yaml
    - src/train/train_and_evaluate.py
    - src/train/run_train.py
    outs:
    - mlruns

  find_best_model:
    cmd: python3 -m src.train.challenger_model
    deps:
      - src/train/challenger_model.py
      - src/train/run_train.py
      - mlruns
      - params.yaml
    outs:
      - deployment/model_version.json

  report:
    cmd: python3 -m src.train.generate_cml_report
    deps:
      - src/train/generate_cml_report.py
      - src/train/challenger_model.py
      - src/train/run_train.py
      - params.yaml
      - mlruns
    outs:
      - reports/compare_metrics.json
      - reports/compare_confusion_matrices.png
      - reports/best_model_metrics.json
      - reports/best_model_confusion_matrix.png
