stages:
  check_for_new_data:
    cmd: python3 src/data/check_for_new_data.py
    params:
      - download.url
      - download.last_updated
    deps:
      - params.yaml
    outs:
      - data/last_updated.txt

  collect_data:
    cmd: python3 src/data/collect_and_extract.py ${download.url} --out ${download.out}
    params:
      - download.url
      - download.out
    deps:
      - src/data/collect_and_extract.py
      - params.yaml
      - data/last_updated.txt
    outs:
      - data/raw/creditcard.csv

  preprocess:
    cmd: python3 src/data/preprocess.py
    deps:
      - data/raw/creditcard.csv
      - src/data/preprocess.py
    params:
      - preprocess.raw_data_path
      - preprocess.processed_data_path
      - preprocess.scale_columns
    outs:
      - data/processed/processed_creditcard.csv

  split:
    cmd: python3 src/train/split.py
    deps:
      - src/train/split.py
      - data/processed/processed_creditcard.csv
    params:
      - split.processed_data_path
      - split.split_data_path
      - split.target_column
      - split.test_size
      - split.random_state
    outs:
    - data/split/train_raw.npz
    - data/split/train_balanced.npz
    - data/split/test.npz