download:
  url: "https://www.kaggle.com/api/v1/datasets/download/mlg-ulb/creditcardfraud"
  out: "data/raw"
  last_updated: "data/last_updated.txt"

preprocess:
  raw_data_path: data/raw/creditcard.csv
  processed_data_path: data/processed/processed_creditcard.csv
  target_column: Class
  scale_columns: ["Time", "Amount"]

split:
  processed_data_path: data/processed/processed_creditcard.csv
  split_data_path: data/split
  target_column: Class
  test_size: 0.2
  random_state: 42

model:
  n_estimators: 100
  max_depth: null
  random_state: 42