download:
  url: "https://www.kaggle.com/api/v1/datasets/download/mlg-ulb/creditcardfraud"
  out: "data/raw"
  last_updated: "data/last_updated.txt"

preprocess:
  raw_data_path: data/raw/creditcard.csv
  processed_data_path: data/processed/processed_creditcard.csv
  target_column: Class
  scale_columns: ["Time", "Amount"]