name: Deploy and Test Fraud API

on:
  workflow_run:
    workflows: ["Train, Evaluate and Report"]
    types:
      - completed

jobs:
  deploy_and_test_container:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t fraud-api .

      - name: Run Docker container
        run: |
          docker run -d -p 8000:8000 --name fraud-api fraud-api
          sleep 10  # Give time for API to start

      - name: Test /predict endpoint with curl
        run: |
          curl -X POST http://localhost:8000/predict \
            -H "Content-Type: application/json" \
            -d '{
              "Time": -0.5073720321, "V1": -16.5265065691, "V2": 8.5849717959, "V3": -18.6498531852,
              "V4": 9.5055935151, "V5": -13.7938185271, "V6": -2.8324042994, "V7": -16.701694296,
              "V8": 7.5173439037, "V9": -8.5070586368, "V10": -14.1101844415, "V11": 5.2992363496,
              "V12": -10.8340064815, "V13": 1.6711202533, "V14": -9.3738585836, "V15": 0.3608056416,
              "V16": -9.8992465408, "V17": -19.2362923698, "V18": -8.3985519949, "V19": 3.1017353689,
              "V20": -1.5149234353, "V21": 1.1907386948, "V22": -1.127670009, "V23": -2.3585787698,
              "V24": 0.673461329, "V25": -1.4136996746, "V26": -0.4627623614, "V27": -2.0185752488,
              "V28": -1.0428041697, "Amount": 4.7815272829
            }'

      - name: Stop and remove Docker container
        if: always()
        run: docker rm -f fraud-api
