name: MLOps Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: write-all

jobs:
  train_and_report_eval_performance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Or wherever flake8 is listed

      - name: Lint with flake8 # The flake8 library was installed as a dependency in the requirements.txt file
        run: flake8 src tests --statistics

      - name: Run unit tests with pytest
        run: PYTHONPATH=src pytest -v --cov=src --cov-report=term-missing

      # Setup CML GitHub Action
      - name: Setup CML
        uses: iterative/setup-cml@v1

      - name: Reproduce DVC pipeline
        run: |
          echo "🧪 Running DVC pipeline..."
          dvc repro

      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Add metrics data to markdown
          cat metrics.json >> model_eval_report.md
          
          # Add confusion matrix plot to markdown
          echo "![confusion matrix plot](./confusion_matrix.png)" >> model_eval_report.md

          # Create comment from markdown report
          cml comment create model_eval_report.md

      

